name: sound_clean
description: Sound clean mobile app
publish_to: none

version: 1.0.0+1000000

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  easy_localization: 3.0.1
  equatable: 2.0.5
  flutter_native_splash: 2.2.17 
  flutter_bloc: 8.1.2
  fluttertoast: 8.1.2
  just_audio: 0.9.31
  path_provider: 2.0.12
  package_info_plus: 3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/icons/
    - lib/assets/sounds/
    - lib/assets/fonts/
    - lib/assets/localization/

  
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Regular.ttf
